### ISSUE TITLE
Fail to start the project with ./gradlew run

### ISSUE THREAD

**Issue by MaBeuLux88** [mongodb-developer/getting-started-search-java#2]
![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/26a1409b-c998-4027-8997-06ac5c6447fc)

**Comment by erikhatcher** [comment]
Do you have a `default` index?

**Comment by MaBeuLux88** [comment]
No because the blog post didn't mention it. Only the README said to create a default index but without an index definition. I'm not sure what I was doing or starting to be honest. 

If you have 2 blog posts in the same repo, make it clear in the README as well. 
Link back to the online posts if you can or plan to add the links once it's online. 

The README did say to create an index definition though but I though it would start the service even without one. Or at least the error msg could be more clear.

The demon is in details =)

**Comment by erikhatcher** [comment]
indeed... in the details.

**Comment by erikhatcher** [comment]
Good points.  I've added some clarifications into the README in commit 36a84cd0ffda6e6ffefcaa8ef2c56b3b66a21d8a
