### ISSUE TITLE
UI HTML could be improved

### ISSUE THREAD

**Issue by MaBeuLux88** [mongodb-developer/getting-started-search-java#3]
I was promised a search box & some data presentation layer ;-)

![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/fa0ba1e5-748c-45c5-80c7-866f884f804a)

**Comment by erikhatcher** [comment]
Where was that promise?  lol - but, good point and will take to heart here.

**Comment by MaBeuLux88** [comment]
![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/c6f550a4-b83a-4eaf-b9fc-07398789f1a8)
 you set the expectations high :+1: 

No big deal at all though, it works. People get it. 

I'll be writing a blog post like that with some React front end probably though so don't worry - be happy.

**Comment by erikhatcher** [comment]
The server part of this repo has been moved to its own repo, and this ticket migrated to https://github.com/mongodb-developer/atlas-search-java-server/issues/1
