### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by MaBeuLux88** [mongodb-developer/getting-started-search-java#4]
- Which version of Java are you targeting ? This doesn't seem explicit in the `build.gradle`.
- Why is `index_config.json` in the webapp folder? It's just here for reference, no? Move this in the README.md instead?
- It's not clear to me why you have 2 files FirstSearchExample and SearchServlet? Looks like the blog post is just about the servlet one so why keep the other one in the code?
- Logger improvements: 

```java
private static final Logger LOGGER = LoggerFactory.getLogger(MasterKeyServiceImpl.class);
then 
LOGGER.info("=> Person not found: {}", e.toString());
```

- fix some warnings
![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/324361f2-2e3e-4c9e-b830-fba3c43999c2)

![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/1a80e6f8-caba-49cf-8254-23def70dd59a)

Looks like the "close" of the MDB connection isn't handled correctly when the program stops

![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/754812cd-98bd-4c99-a495-804ea7fb42df)

- Don't use `Arrays.asList` if you are using `List.of` in some places. Prefer List.of in my opinion now. 

![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/a6797a08-7d99-4687-8a9e-0d6ff3bb81d7)

![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/1b3e2f51-293b-43ca-b77f-4eff7c513f83)

I know it's not true because you have handled the errors but try to reorg the code a little bit so Java knows that maybe are removed the false warning?

- I think I would make some methods to make the code easier to read. 

![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/1c48f75f-347a-4f72-a335-16b821de8856)

- some code unused on purpose?
![image](https://github.com/mongodb-developer/getting-started-search-java/assets/7153911/7271876c-47e4-495e-a373-509939bcb98d)

**Comment by MaBeuLux88** [comment]
Use camelCase everywhere in var names `project_fields`, `project_fields_value`, `search_path`, ...

**Comment by erikhatcher** [comment]
Thank you for the nudge on the warnings.  The `q` one annoyed me because I knew it wasn't true, but I'll re-org to be cleaner as you recommend.  I like your style.  Except when it comes to variable names!  But I'll adjustThoseToBeAsYouAndJavaWish too.

**Comment by MaBeuLux88** [comment]
It's not me, it's Java :coffee: !

**Comment by erikhatcher** [comment]
Variable names "Max-ified" in commit 9c51b652593f37cb525c0fe2f01e6aa6120448c3

**Comment by erikhatcher** [comment]
Which version of Java are you targeting?: I'm running 17.0.8 on command-line and 17.0.4 in my IDE (IntelliJ). Should I be specifying a particular version somewhere?  Maybe just in the README?

**Comment by erikhatcher** [comment]
`Why is index_config.json in the webapp folder? It's just here for reference, no? Move this in the README.md instead?` - DONE, moved to in-line JSON block in README. Good call.  In commit e5e2cd90a9717781af50c0a16097c4838868b142

**Comment by erikhatcher** [comment]
All warnings addressed.  Variables renamed.  JSON file moved to README. Logger issues addressed.  Should be all good here now.  Lemme know if I missed anything, @MaBeuLux88  - thanks!
